name: youtube_poll
description: Continuously poll the YouTube website to get new videos.
version: 0.2.1
repository: https://github.com/Ampless/youtube_poll

environment:
  sdk: ^3.0.0

dependencies:
  youtube_explode_dart: ^2.2.1

dev_dependencies:
  lints: ^4.0.0
  #tested: ^1.0.0
